// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTA1CQN_Qs6fL1j1qWWcAhqJNM52zMbRM',
    appId: '1:566802056091:web:78ed290364772790a4d73e',
    messagingSenderId: '566802056091',
    projectId: 'work-hub-7610d',
    authDomain: 'work-hub-7610d.firebaseapp.com',
    storageBucket: 'work-hub-7610d.appspot.com',
    measurementId: 'G-1JZENYJKB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkltPN1wvyt_F5csLhXusbQ02dNDuhYVQ',
    appId: '1:566802056091:android:a25511d11d8f75a5a4d73e',
    messagingSenderId: '566802056091',
    projectId: 'work-hub-7610d',
    storageBucket: 'work-hub-7610d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx70H3HMvVqv6b4hwqmE5noYK_OymsuSw',
    appId: '1:566802056091:ios:18001d30349ed082a4d73e',
    messagingSenderId: '566802056091',
    projectId: 'work-hub-7610d',
    storageBucket: 'work-hub-7610d.appspot.com',
    iosBundleId: 'com.example.workhubWeb',
  );
}
